### ISSUE TITLE
[3rd 08PP] Finish final fabrication

### ISSUE THREAD

**Issue by rocco8773** [rocco8773/gaps_work#12]
Finish fabrication of 3rd 08PP

- [x] Prep 62 paddle spacers
- [x] Process 4 Top Straps
- [x] Sanded foam panel
- [x] epoxy inserts
- [x] epoxy paddle spacers to foam panel
- [x] epoxy paddle spacers to top straps
- [x] #8 (can still be done after strapping)
- [x] #9
