### ISSUE TITLE
[1st 08PP] Finish final fabrication

### ISSUE THREAD

**Issue by rocco8773** [rocco8773/gaps_work#15]
Finish fabrication of 3rd 08PP

- [x] Prep 62 paddle spacers
- [x] Process 4 Top Straps
- [x] Sanded foam panel
- [x] epoxy inserts
- [x] epoxy paddle spacers to foam panel
- [x] epoxy paddle spacers to top straps
- [x] #6 (can still be done after strapping)

**Comment by rocco8773** [comment]
Leaving this open for now, because we might want to add more epoxy to one corner of the foam panel to build up the small bit of missing foam.
