### ISSUE TITLE
[4th 08PP] Finish final fabrication

### ISSUE THREAD

**Issue by rocco8773** [rocco8773/gaps_work#2]
Finish fabrication of 4th 08PP

- [x] #10
- [x] Process 4 Top Straps
- [x] Sanded foam panel
- [x] epoxy inserts
- [x] epoxy paddle spacers to foam panel
- [x] #16 
- [x] #11 (can still be done after strapping)

**Comment by rocco8773** [comment]
Epoxying paddles spacers to top straps started today.

**Comment by rocco8773** [comment]
We need 20 more paddle spacers to be processed
