### ISSUE TITLE
[1st 10PP] Finish final fabrication

### ISSUE THREAD

**Issue by rocco8773** [rocco8773/gaps_work#86]
- [ ] Process 80 paddle spacers
- [ ] Process Top Straps
- [ ] Epoxy inserts
- [ ] Epoxy corners
- [ ] Epoxy paddle spacers to foam board
- [ ] Epoxy paddle spacers to Top Straps

**Comment by rocco8773** [comment]
7 Mar. 2023

- Everything is epoxied
- Hardware has been removed, except for a few snapped screws
- Snapped screws need to be removed from top straps
- Panel and Top Straps need to be cleaned
